main: main.o maxheap.o heap.o swap.o
	gcc -g -o main main.o maxheap.o heap.o swap.o
main.o: main.c
	gcc -g -c main.c -o main.o
heap.o: heap.c
	gcc -g -c heap.c -o heap.o
maxheap.o: maxheap.c
	gcc -g -c maxheap.c -o maxheap.o
swap.o: swap.c
	gcc -g -c swap.c -o swap.o
